name: Publish Package

on:
  push:
    tags:
      - "packages/reactotron-react-query@*"

jobs:
  publish:
    name: Publish reactotron-react-query to npm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org/"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Ensure tag is from main branch and by trusted user
        run: |
          TRUSTED_USER="hsndmr"

          if [ "$GITHUB_ACTOR" != "$TRUSTED_USER" ]; then
            echo "Unauthorized user: $GITHUB_ACTOR. Only $TRUSTED_USER can publish."
            exit 1
          fi

          git fetch origin main --depth=1

          BRANCH=$(git branch -r --contains ${{ github.sha }} | grep origin/main || true)
          if [ -z "$BRANCH" ]; then
            echo "Tag is not from main branch. Aborting publish."
            exit 1
          fi

          echo "Tag is from main branch and user is authorized. Continuing."

      - name: Copy root files into package
        run: |
          cp README.md CHANGELOG.md ./packages/reactotron-react-query/

      - name: Build package
        run: pnpm --filter reactotron-react-query build

      - name: Publish package
        run: pnpm --filter reactotron-react-query publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
