name: Publish Package

on:
  push:
    branches:
      - main
    tags:
      - "packages/reactotron-react-query@*"

jobs:
  publish:
    name: Publish reactotron-react-query to npm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org/"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Copy root files into package
        run: |
          cp README.md CHANGELOG.md ./packages/reactotron-react-query/

      - name: Build package
        run: pnpm --filter reactotron-react-query build

      - name: Publish package
        run: pnpm --filter reactotron-react-query publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
